[admiral]
items = [
    "clock",
    "left",
    "workspaces",
    "right",
    "left",
    "klay",
    "right",
    "left",
    "network" ,
    "right" 
] 

[workspaces]
path = 'tail -f /tmp/ws_out.fifo 2>/dev/null'

[klay]
path = "/home/neg/bin/mon/klay2"
reload = 0.1

[clock]
path = "~/bin/scripts/wrp.sh $(date '+%H:%M')"
reload = 1

[network]
path = '~/bin/mon/network_speed.sh enp7s0 2'

[left]
path = "~/bin/scripts/wrp.sh __left__"
static = true

[right]
path = "~/bin/scripts/wrp.sh __right__"
static = true
