[admiral]
items = [
    "left"   , "clock"      , "right"   ,
    "left"   , "workspaces" , "right"   ,
    "left"   , "input"      , "klay"    , "right" ,
    # "left" , "cpu"        , "cpumon"  , "right" ,
    # "left" , "mail"       , "mailmon" , "right" ,
    "left"   , "network"    , "right"
] 

[workspaces]
path = 'tail -f /tmp/ws_out.fifo 2>/dev/null'

[klay]
path   = "~/bin/mon/klay"

# [cpu]
# path = "echo 'cpu: '"
# static = true

# [cpumon]
# path = '~/bin/mon/cpu.sh'

# [mail]
# path = "echo 'mail: '"
# static = true

# [mailmon]
# path = '~/bin/scripts/mail/mail_count.zsh'

[clock]
path   = "date '+%H:%M'"
reload = 1

[network]
path = '~/bin/mon/network_speed.sh'

[input]
path   = "echo 'input: '"
static = true

[left]
path   = "~/bin/scripts/wrp.sh __left__"
static = true

[right]
path   = "~/bin/scripts/wrp.sh __right__"
static = true
