scriptencoding utf-8
set shell=/bin/sh
if has('vim_starting')
  set nocompatible  "be improved
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
"--[ Main ]--------------------------------------------------------------------------------------------------
NeoBundle 'Valloric/YouCompleteMe' "ycm is awesome completer for c,cpp with clang, c#,jedi-python,etc
NeoBundle 'neg-serg/vim-colors' "all colors which I want
NeoBundle 'Shougo/vimproc' "vimproc is for faster work of unite
NeoBundle 'Shougo/neomru.vim.git' "mru for unite
NeoBundle 'vim-jp/vital.vim.git' "improve unite perf
NeoBundle 'Shougo/unite.vim.git' "unite for creating ui
NeoBundle 'neg-serg/unite-all-in-one.git' "plugins for unite which I use
NeoBundle 'neg-serg/vim-like-emacs' "add some bindings from readline and emacs for nice vim editing
NeoBundle 'rhysd/vim-clang-format.git' "format code by clang, better that astyle -A14
NeoBundle 'sjbach/lusty.git' "file/buffer explorer
NeoBundle 'SirVer/ultisnips.git' "Snippets with ycm compatibility
NeoBundle 'junegunn/vim-easy-align' "easy tabular
NeoBundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim'}
if executable("ack")
NeoBundle 'mileszs/ack.vim' "ack wrapper
endif
if executable("ag")
NeoBundle 'rking/ag.vim.git' "ag (ack replacement) wrapper
endif
NeoBundle 'tpope/vim-repeat' "repeat everything!
NeoBundle 'sjl/gundo.vim' " browse the vim undo tree
NeoBundle 'tpope/vim-eunuch.git' "for SudoWrite, Locate, Find etc
NeoBundle 'Raimondi/delimitMate.git' "Add pairs to brackets
NeoBundle 'scrooloose/syntastic.git' "syntax checker. Realtime with ycm
NeoBundle 'nathanaelkane/vim-indent-guides' "indent tabs visually with |-es too slow
NeoBundle 'scrooloose/nerdtree.git' "for cwd
"--[ dcvs ]--------------------------------------------------------------------------------------------------
NeoBundle 'tpope/vim-git' "syntax, indent, and filetype plugin files for git
if executable("git")
NeoBundle 'rhysd/conflict-marker.vim' "jumps over merge conflicts
NeoBundle 'tpope/vim-fugitive.git' "Git stuff. Needed for powerline etc
NeoBundle 'kablamo/vim-git-log.git' "Git commit browser/log wrapper
NeoBundle 'gregsexton/gitv' "Git viewer
NeoBundle 'junegunn/vim-github-dashboard.git' "Git dashboard in vim
NeoBundle 'jaxbot/github-issues.vim.git' "github issues autocomp
NeoBundle 'idanarye/vim-merginal.git' "to handle branches/merge conflicts
"--[ be careful with fugitive ]------------------------------------------------------------------------------
NeoBundle 'sjl/splice.vim.git' "Merge tool for vim
endif
"------------------------------------------------------------------------------------------------------------
if executable("tmux")
NeoBundle 'tpope/vim-tbone.git' "tmux basics
NeoBundle 'benmills/vimux.git' "exec commands in tmux
NeoBundle 'christoomey/vim-tmux-navigator' "easy jump between windows
NeoBundle 'wellle/tmux-complete.vim.git' "completion from tmux for vim
endif
" NeoBundle 'sjl/clam.vim.git' "Allow run commands in split
NeoBundle 'Shougo/vimshell.vim.git' "fast shell implementation
NeoBundle 'tpope/vim-dispatch.git' "Should provide async build
if (executable("ghci") && executable("ghcmod"))
NeoBundle 'ujihisa/neco-ghc' "autocomplete for hs using ghc-mod
endif                                        
NeoBundle 'travitch/hasksyn' "simple highlight for normal haskell code
NeoBundle 'derekwyatt/vim-scala' "different initial scala support for vim
NeoBundle 'derekwyatt/vim-sbt' "basic SBT support for vim
"--[ misc ]--------------------------------------------------------------------------------------------------
NeoBundle 'drmikehenry/vim-fixkey' "fixes key codes for console Vim
NeoBundle 'ReekenX/vim-rename2.git' "rename for files even with spaces in filename
NeoBundle 'thinca/vim-ref.git' "integrated reference viewer man/perldoc etc
NeoBundle 'othree/eregex.vim' "Perl-like extended regex for vim
NeoBundle 'chrisbra/Join.git' "Extended and fast Join for vim
NeoBundle 'vim-scripts/bufkill.vim.git' "bufkill with BD
NeoBundle 'lyokha/vim-xkbswitch.git' "Autoswitch on <esc> with libxkb needs xkb-switch-git to run
NeoBundle 'tpope/vim-surround' "is all about surroundings: parentheses, brackets, quotes, XML tags, and more
NeoBundle 'vim-scripts/YankRing.vim.git' "multiple pasting
"--[ dev ]---------------------------------------------------------------------------------------------------
NeoBundle 'majutsushi/tagbar' "tagbar
NeoBundle 'tomtom/tcomment_vim.git' "easier comments
NeoBundle 'tpope/vim-endwise' "to insert endif for if, end for begin and so on in ruby
NeoBundle 'matchit.zip' "Improves % match for everything
NeoBundle 'tpope/vim-unimpaired.git' "good mappings and toggles
NeoBundle 'dbakker/vim-projectroot' "better rooter
NeoBundle 'Valloric/ListToggle.git' "toggle quickfix and location list <leader>l by def
NeoBundle 'derekwyatt/vim-fswitch.git' "switching between companion source files (e.g. .h and .cpp)
NeoBundle 'vim-scripts/IndentConsistencyCop.git' "autochecks for indent
NeoBundle 'hynek/vim-python-pep8-indent.git' "python autoindent pep8 compatible
NeoBundle 'gilligan/tern_for_vim.git' "js-omni completion
if executable("lldb")
NeoBundle 'gilligan/vim-lldb.git' "lldb-plugin for vim
endif
if executable("mono")
NeoBundle 'nosami/Omnisharp.git' "omnisharp completion
endif
NeoBundle 'jnwhiteh/vim-golang.git' "golang syntax highlight
NeoBundle 'jstemmer/gotags.git' "tags for go
if executable("go")
NeoBundle 'Blackrush/vim-gocode.git' "omnicomplete for go
endif
NeoBundle 'wting/rust.vim' "rust bindings for vim syntax hi
NeoBundle 'vim-scripts/taglist.vim.git' "show taglist
"---------------[  Tags  ]-----------------------------------------------------------------------------------
if executable("gtags")
NeoBundle 'yuki777/gtags.vim.git' "Gtags v0.64
NeoBundle 'vim-scripts/multiwindow-source-code-browsing.git' "gtag multiwindow
NeoBundle 'bbchung/gasynctags.git' "autogenerate gtags to cscope db
endif
"--[ latex ]-------------------------------------------------------------------------------------------------
NeoBundle 'vim-scripts/auctex.vim.git' "auctex.vim for the syntax highlighting.
NeoBundle 'vim-scripts/TeX-9.git' "tex autocompetion
NeoBundle 'xuhdev/vim-latex-live-preview.git' "tex live preview
"--[ web ]---------------------------------------------------------------------------------------------------
" NeoBundle 'Valloric/vim-instant-markdown' "realtime markdown preview
" NeoBundle 'tpope/vim-markdown' "markdown helper for vim
" NeoBundle 'Valloric/xmledit' "xml editing
"---------------[ other filetypes ]--------------------------------------------------------------------------
NeoBundle 'vimez/vim-tmux' "syntax hi for tmux
NeoBundle 'elzr/vim-json' "syntax hi for json format
NeoBundle 'rsmenon/vim-mathematica.git' "Mathematica syntax and omnicomp

call neobundle#end()

syntax on
filetype plugin indent on

NeoBundleCheck

source ~/.vim/00-functions.vim
source ~/.vim/01-settings.vim
source ~/.vim/02-unite.vim
source ~/.vim/04-autocmds.vim
source ~/.vim/10-keymaps.vim
source ~/.vim/21-langmap.vim
