"  __     ___
"  \ \   / (_)_ __ ___
"   \ \ / /| | '_ ` _ \
"    \ V / | | | | | | |
"     \_/  |_|_| |_| |_|
"

scriptencoding utf-8
 if has('vim_starting')
  set nocompatible               " Be iMproved
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

try
call neobundle#rc(expand('~/.vim/bundle/'))
if empty($https_proxy)
  let g:neobundle#types#git#default_protocol = 'git'
else
  let g:neobundle#types#git#default_protocol = 'https'
endif

NeoBundleFetch 'Shougo/neobundle.vim'         " Let NeoBundle manage NeoBundle
"------------------------------------------------------------------------------------------------------------
"--[ Main ]--------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'https://bitbucket.org/ns9tks/vim-l9' "Utility library for vim
NeoBundle 'Valloric/YouCompleteMe'            "ycm is awesome completer for c,cpp with clang, c#,jedi-python,etc
NeoBundle 'sjbach/lusty.git'                  "file/buffer explorer
NeoBundle 'SirVer/ultisnips.git'              "Snippets with ycm compatibility
NeoBundle 'godlygeek/tabular'                 "tabularize!
NeoBundle 'junegunn/vim-easy-align'           "easy tabular
NeoBundle 'mileszs/ack.vim'                   "ack wrapper
if executable("ag")
    NeoBundle 'rking/ag.vim.git'              "ag (ack replacement) wrapper
endif
NeoBundle 'tpope/vim-repeat'                  "repeat everything!
" browse the vim undo tree
NeoBundleLazy 'sjl/gundo.vim', { 'autoload' : {'commands': 'GundoToggle'}}
NeoBundle 'tpope/vim-eunuch.git'              "for SudoWrite, Locate, Find etc
NeoBundle 'Raimondi/delimitMate.git'          "Add pairs to brackets
NeoBundle 'scrooloose/syntastic.git'          "syntax checker. Realtime with ycm
NeoBundle 'bling/vim-airline.git'             "fancy statusline
NeoBundle 'nathanaelkane/vim-indent-guides'   "indent tabs visually with |-es too slow
NeoBundle 'xolox/vim-misc'                    "for vim notes
NeoBundle 'xolox/vim-easytags.git'            "easy autoupdate and highlight for ctags
NeoBundle 'scrooloose/nerdtree.git'           "for cwd
NeoBundle 'Shougo/vimproc', {
      \ 'build' : {
      \     'windows' : 'make -f make_mingw32.mak',
      \     'cygwin'  : 'make -f make_cygwin.mak',
      \     'mac'     : 'make -f make_mac.mak',
      \     'unix'    : 'make -f make_unix.mak',
      \    },
      \ }
" NeoBundle 'Shougo/context_filetype.vim.git'   "filetype autoset
NeoBundle 'jszakmeister/vim-togglecursor.git'
NeoBundle 'shaneharper/vim-rtags.git'
"------------------------------------------------------------------------------------------------------------
"--[ Sessions ]----------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'tpope/vim-obsession.git'           "Session manager
NeoBundle 'xolox/vim-session.git'             "More powerful session manager
"------------------------------------------------------------------------------------------------------------
"--[ DCVS ]--------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'tpope/vim-fugitive.git'            "Git stuff. Needed for powerline etc
NeoBundle 'int3/vim-extradite'                "Git commit browser/log wrapper for vim
NeoBundle 'gregsexton/gitv'                   "Git viewer
NeoBundle 'junegunn/vim-github-dashboard.git' "Git dashboard in vim
NeoBundle 'vim-scripts/compview.git'          "interactive search
NeoBundle 'tpope/vim-git'                     "syntax, indent, and filetype plugin files for git
NeoBundle 'jaxbot/github-issues.vim.git'      "github issues autocomp
"--[ Be careful with fugitive ]------------------------------------------------------------------------------
NeoBundle 'sjl/splice.vim.git'                "Merge tool for vim
"------------------------------------------------------------------------------------------------------------
"--[ tmux ]--------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'tpope/vim-tbone.git'               "another tmux wrapper for vim
NeoBundle 'epeli/slimux.git'                  "tmux wrapper with gvim support
NeoBundle 'benmills/vimux.git'                "tmux wrapper
"------------------------------------------------------------------------------------------------------------
"--[ haskell ]-----------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundleLazy 'ujihisa/neco-ghc'             "autocomplete for hs using ghc-mod
    \ {'autoload': {'filetypes': 'hs'}}
NeoBundleLazy 'travitch/hasksyn'             "simple highlight for normal haskell code
    \ {'autoload': {'filetypes': 'hs'}}
"------------------------------------------------------------------------------------------------------------
"--[ java/scala ]--------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundleLazy 'derekwyatt/vim-scala'         "different initial scala support for vim
    \ {'autoload': {'filetypes': 'scala'}}
NeoBundleLazy 'derekwyatt/vim-sbt'           "basic SBT support for vim
    \ {'autoload': {'filetypes': 'scala'}}
" NeoBundle 'tpope/vim-classpath'            "sets path for jvm
"------------------------------------------------------------------------------------------------------------
"--[ misc ]--------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'drmikehenry/vim-fixkey'            "fixes key codes for console Vim
NeoBundle 'ReekenX/vim-rename2.git'           "rename for files even with spaces in filename
NeoBundle 'thinca/vim-ref.git'                "integrated reference viewer man/perldoc etc
NeoBundle 'tyru/restart.vim.git'              "add restart support
NeoBundle 'othree/eregex.vim'                 "Perl-like extended regex for vim
NeoBundle 'chrisbra/Join.git'                 "Extended and fast Join for vim
NeoBundle 'vim-scripts/bufkill.vim.git'       "bufkill with BD
NeoBundle 'lyokha/vim-xkbswitch.git'          "Autoswitch on <esc> with libxkb needs xkb-switch-git to run
NeoBundle 'tpope/vim-surround'                "is all about surroundings: parentheses, brackets, quotes, XML tags, and more
NeoBundle 'tpope/vim-repeat'                  " .(dot) for surround.vim speeddating.vim abolish.vim unimpaired.vim commentary.vim
NeoBundle 'vim-scripts/utl.vim.git'           "Open urls in files
NeoBundle 'tpope/vim-vinegar.git'             "some wrapper to netrw for projects
NeoBundle 'vim-scripts/YankRing.vim.git'      "multiple pasting
"------------------------------------------------------------------------------------------------------------
"--[ colorschemes ]------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'altercation/vim-colors-solarized'  "fancy solarized colorscheme
NeoBundle 'reedes/vim-colors-pencil.git'      "fancy pencil dark and light colorscheme
NeoBundle 'chriskempson/base16-vim'           "set of good colorschemes
NeoBundle 'nanotech/jellybeans.vim.git'       "fancy jellybeans colorsheme
"------------------------------------------------------------------------------------------------------------
"--[ dev ]---------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'majutsushi/tagbar'                 "tagbar
NeoBundle 'tomtom/tcomment_vim.git'           "easier comments
NeoBundle 'terryma/vim-multiple-cursors'      "it's feeric!!111
NeoBundleLazy 'salsifis/vim-transpose', { 'autoload' :
            \ { 'commands' : 'Transpose'}}
NeoBundle 'lord-garbage/tslime.vim.git'       "to work with lisp, clojure, f#
NeoBundle 'tpope/vim-endwise'                 "to insert endif for if, end for begin and so on in ruby
NeoBundle 'matchit.zip'                       "Improves % match for everything
NeoBundle 'tpope/vim-unimpaired.git'          "good mappings and toggles
NeoBundle 'dbakker/vim-projectroot'           "better rooter
NeoBundle 'Valloric/ListToggle.git'           "toggle quickfix and location list <leader>l by def
NeoBundle 'derekwyatt/vim-fswitch.git'        "switching between companion source files (e.g. .h and .cpp)
NeoBundle 'vim-scripts/IndentConsistencyCop.git' "autochecks for indent
NeoBundle 'vim-scripts/perl-support.vim.git'  "perl-support for vim
NeoBundle 'xolox/vim-lua-ftplugin.git'        "lua support for vim
NeoBundle 'hari-rangarajan/CCTree'            "call-tree for c
NeoBundle 'hynek/vim-python-pep8-indent.git'  "python autoindent pep8 compatible
NeoBundle 'gilligan/tern_for_vim.git'         "js-omni completion
NeoBundle 'gilligan/vim-lldb.git'             "lldb-plugin for vim
NeoBundle 'nosami/Omnisharp.git'              "omnisharp completion
NeoBundle 'jeetsukumaran/vim-buffersaurus.git' "search and replace between buffers
NeoBundle 'jnwhiteh/vim-golang.git'           "golang syntax highlight
NeoBundle 'Blackrush/vim-gocode.git'          "omnicomplete for go
NeoBundle 'jstemmer/gotags.git'               "tags for go
"------------------------------------------------------------------------------------------------------------
"--[ shell integration ]-------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
" NeoBundle 'vim-scripts/Conque-GDB.git'        "Conque GDB is powerful gdb wrapper for vim
" NeoBundle 'oplatek/Conque-Shell.git'          "Possibly it's shell for gvim
NeoBundle 'sjl/clam.vim.git'                  "Allow run commands in split
NeoBundle 'Shougo/vimshell.vim.git'           "fast shell implementation
NeoBundle 'pydave/AsyncCommand.git'           "Async exec for grep, shell, make and others
NeoBundle 'tpope/vim-dispatch.git'            "Should provide async build
"------------------------------------------------------------------------------------------------------------
"--[ latex ]-------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'vim-scripts/auctex.vim.git'        "auctex.vim for the syntax highlighting.
NeoBundle 'vim-scripts/TeX-9.git'             "tex autocompetion
NeoBundle 'xuhdev/vim-latex-live-preview.git' "tex live preview
"------------------------------------------------------------------------------------------------------------
"--[ web ]---------------------------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'Valloric/vim-instant-markdown'     "realtime markdown preview
NeoBundle 'tpope/vim-markdown'                "markdown helper for vim
NeoBundle 'Valloric/xmledit'                  "xml editing
" NeoBundleLazy 'othree/html5.vim', {'autoload': {'filetypes': ['html', 'xml','css']}}
" "highlight for html
" NeoBundleLazy 'Valloric/MatchTagAlways', {'autoload': {'filetypes': ['html', 'xhttml','xml']}}
" NeoBundleLazy 'jimenezrick/vimerl', {'autoload': {'filetypes': 'erl'}}
" NeoBundleLazy 'mattn/emmet-vim', {'autoload':  {'filetypes': ['html', 'xhttml', 'css', 'xml', 'xls', 'markdown']}}
" NeoBundleLazy 'hail2u/vim-css3-syntax', {'autoload': {'filetypes': ['html', 'xhttml', 'css', 'xml', 'xls', 'markdown']}}
" NeoBundleLazy 'skammer/vim-css-color', {'autoload': {'filetypes': ['html', 'xhttml', 'css', 'xml']}}
" NeoBundleLazy 'matthias-guenther/hammer.vim', {'autoload': \ {'filetypes': ['html', 'xhttml', 'css']}}
" NeoBundleLazy 'mattn/zencoding-vim', {'autoload': {'filetypes': ['html', 'xhttml','xml']}}
"------------------------------------------------------------------------------------------------------------
"---------------[  textobj  ]--------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
" NeoBundle 'paradigm/TextObjectify'            "Textjob main plugin
" NeoBundle 'kana/vim-textobj-entire.git'       "Text objects to select the entire content of a buffer
" NeoBundle 'kana/vim-textobj-indent.git'       "Textobj for indented block of lines
" NeoBundle 'kana/vim-textobj-lastpat.git'      "Textobj for the last searched pattern
" NeoBundle 'kana/vim-textobj-line.git'         "Textobj for the current line
" NeoBundle 'kana/vim-textobj-underscore.git'   "Textobj for underscore
" NeoBundle 'kana/vim-textobj-user.git'         "To create your own objects
" NeoBundle 'kana/vim-textobj-entire.git'       "gives you `e` for entire document. so vae, and etc
" NeoBundle 'kana/vim-textobj-function.git'     "gives you `f` textobj. so vaf to select a function
" NeoBundle 'vim-scripts/argtextobj.vim.git'    "This plugin provides a text-object 'a' (argument)
"------------------------------------------------------------------------------------------------------------
"---------------[  unite  ]----------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
NeoBundle 'vim-jp/vital.vim.git'              "improve unity perf
NeoBundle 'Shougo/unite.vim.git'              "Unite for autocomp
NeoBundle 'Shougo/neomru.vim.git'             "MRU plugin for unite
" NeoBundle 'junkblocker/unite-codesearch.git'  "for google-codesearch
"--[ Create temporary file for memo, testing, ... ]----------------
NeoBundleLazy 'Shougo/junkfile.vim', { 'autoload':{'commands':'JunkfileOpen', 'unite_sources':['junkfile','junkfile/new']}} 
NeoBundleLazy 'Shougo/unite-build.git', {'autoload' : { 'unite_sources' : 'build', }}
NeoBundleLazy 'Shougo/unite-outline', {'autoload':{'unite_sources':'outline'}}
NeoBundleLazy 'kmnk/vim-unite-svn.git', {'autoload' : { 'unite_sources' : ['svn/status', 'svn/info', 'svn/blame', 'svn/diff'], }}
NeoBundleLazy 'tsukkee/unite-help', {'autoload':{'unite_sources':'help'}}
NeoBundleLazy 'ujihisa/unite-colorscheme', {'autoload':{'unite_sources': 'colorscheme'}}
NeoBundleLazy 'thinca/vim-unite-history', { 'autoload' : { 'unite_sources' : ['history/command', 'history/search']}}
NeoBundleLazy 'osyo-manga/unite-filetype', { 'autoload' : {'unite_sources' : 'filetype', }}
NeoBundleLazy 'osyo-manga/unite-quickfix', {'autoload':{'unite_sources': ['quickfix', 'location_list']}}
NeoBundleLazy 'tacroe/unite-mark', {'autoload':{'unite_sources':'mark'}}
NeoBundleLazy 'mattn/unite-gist.git' , {'autoload':{'unite_sources':'gist'}}
"------------------------------------------------------------------------------------------------------------
"---------------[ other filetypes ]--------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
"--[ Tmux config file syntax ]----------------------------------------
NeoBundleLazy 'vimez/vim-tmux', { 'autoload' : { 'filetypes' : 'conf'}} 
NeoBundleLazy 'joedicastro/vim-pentadactyl', { 'autoload': {'filetypes': ['pentadactyl']}}
NeoBundleLazy 'elzr/vim-json', {'filetypes' : 'json'}
NeoBundleLazy 'vim-scripts/po.vim--gray', {'autoload': {'filetypes': ['po']}}
NeoBundleLazy 'chrisbra/csv.vim', {'autoload' : {'filetypes' : ['csv']}}
" Mathematica syntax and omnicomp
NeoBundleLazy 'rsmenon/vim-mathematica.git', {'autoload' : {'filetypes' : ['mm']}}
" rust bindings for vim syntax hi
NeoBundleLazy 'wting/rust.vim', {'autoload' : {'filetypes' : ['rust']}}
"https://github.com/AndrewRadev/id3.vim.git
"------------------------------------------------------------------------------------------------------------
"---------------[  Tags  ]-----------------------------------------------------------------------------------
"------------------------------------------------------------------------------------------------------------
" Very good navigation, but no stack
NeoBundleLazy 'hewes/unite-gtags.git', {'autoload':{'unite_sources':['gtags', 'gtags/def', 'gtags/context', 'gtags/ref', 'gtags/grep', 'gtags/def' ]}}
NeoBundle 'tranngocthachs/gtags-cscope-vim-plugin.git' "Works great with vim
NeoBundle 'https://bitbucket.org/madevgeny/yate.git'  "Alternative workground to work with cscope

NeoBundleCheck
catch /117/
    echo "load NeoBundle failed"
endtry
syntax on
filetype plugin indent on

source ~/.vim/00-functions.vim
source ~/.vim/01-settings.vim
source ~/.vim/02-unite.vim
source ~/.vim/04-autocmds.vim
source ~/.vim/10-keymaps.vim
source ~/.vim/11-vimacs.vim
source ~/.vim/21-langmap.vim
