-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "web",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<11>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "doc",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<5>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame<1>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "gimp",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "media",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<6>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<6>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [5] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "dev",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<7>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<7>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [6] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "math",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<8>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<2>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [7] = {
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["name"] = "WGroupCW<4>_cwin_sp",
                ["geom"] = {
                    ["y"] = 4,
                    ["x"] = 856,
                    ["w"] = 424,
                    ["h"] = 736,
                },
                ["level"] = 0,
                ["mode"] = 0,
                ["managed"] = {
                },
                ["sizepolicy"] = "free",
            },
            [8] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "vid",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<9>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [9] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "vm",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<4>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<5>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [10] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "fractal",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<9>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [11] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "recoll",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame<3>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [12] = {
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["type"] = "WGroupWS",
                ["name"] = "term",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<10>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<2>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 1,
                                                ["x"] = 1,
                                                ["w"] = 1598,
                                                ["h"] = 876,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 8388617,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1598,
                                                        ["h"] = 876,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                        [2] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["y"] = 1,
                                                ["x"] = 1,
                                                ["w"] = 1598,
                                                ["h"] = 876,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 8388639,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 2,
                                                        ["x"] = 3,
                                                        ["w"] = 1593,
                                                        ["h"] = 872,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [13] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "search",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<11>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame<5>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [14] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["hidden"] = true,
            },
            [15] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "info",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 144,
                    ["x"] = 363,
                    ["w"] = 277,
                    ["h"] = 336,
                },
                ["level"] = 1,
            },
            [16] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "littleterm",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 144,
                    ["x"] = 363,
                    ["w"] = 277,
                    ["h"] = 336,
                },
                ["level"] = 1,
            },
            [17] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "top",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 328,
                    ["x"] = 1010,
                    ["w"] = 270,
                    ["h"] = 306,
                },
                ["level"] = 1,
            },
            [18] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "ncmpcpp",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 323,
                    ["x"] = 585,
                    ["w"] = 897,
                    ["h"] = 390,
                },
                ["level"] = 1,
            },
            [19] = {
                ["level"] = 1,
                ["type"] = "WGroupWS",
                ["name"] = "vm1",
                ["initial_outputs"] = {
                    [1] = "LVDS-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full_bounds",
                ["managed"] = {
                },
                ["unnumbered"] = true,
            },
            [20] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "float",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 325,
                    ["x"] = 674,
                    ["w"] = 692,
                    ["h"] = 407,
                },
                ["level"] = 1,
            },
            [21] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "torrent",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 362,
                    ["w"] = 1238,
                    ["h"] = 758,
                },
                ["level"] = 1,
            },
            [22] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "im",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 108,
                    ["x"] = 1061,
                    ["w"] = 539,
                    ["h"] = 767,
                },
                ["level"] = 1,
            },
        },
    },
}

