-- This file has been generated by notion. Do not edit.
return {
    ["EoCApp*EoCApp"] = {
        ["role"] = "*",
        ["target"] = "WRootWin",
        ["instance"] = "EoCApp",
        ["class"] = "EoCApp",
    },
}

