-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["type"] = "WGroupWS",
                ["name"] = "term",
                ["initial_outputs"] = {
                    [1] = "LVDS-1-0",
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<4>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 1,
                                                ["x"] = 1,
                                                ["w"] = 1598,
                                                ["h"] = 876,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 8388617,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1598,
                                                        ["h"] = 876,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "web",
                ["initial_outputs"] = {
                    [1] = "LVDS-1-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<3>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "media",
                ["initial_outputs"] = {
                    [1] = "LVDS-1-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<1>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "dev",
                ["initial_outputs"] = {
                    [1] = "LVDS-1-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 2,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame<5>",
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [5] = {
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["name"] = "doc",
                ["initial_outputs"] = {
                    [1] = "LVDS-1-0",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<4>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [6] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "torrent",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1590,
                    ["h"] = 412,
                },
                ["level"] = 1,
            },
            [7] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WGroupCW",
                        ["name"] = "WGroupCW<3>",
                        ["geom"] = {
                            ["y"] = 1,
                            ["x"] = 1,
                            ["w"] = 914,
                            ["h"] = 424,
                        },
                        ["switchto"] = true,
                        ["sizepolicy"] = "full",
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["windowid"] = 31457289,
                                ["checkcode"] = 2,
                                ["sizepolicy"] = "full",
                                ["geom"] = {
                                    ["y"] = 0,
                                    ["x"] = 0,
                                    ["w"] = 914,
                                    ["h"] = 424,
                                },
                                ["level"] = 1,
                            },
                        },
                        ["level"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "ncmpcpp",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 256,
                    ["x"] = 492,
                    ["w"] = 916,
                    ["h"] = 426,
                },
                ["level"] = 1,
            },
            [8] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "float2",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 480,
                    ["w"] = 1120,
                    ["h"] = 690,
                },
                ["level"] = 1,
            },
            [9] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "im",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 46,
                    ["x"] = 960,
                    ["w"] = 640,
                    ["h"] = 818,
                },
                ["level"] = 1,
            },
            [10] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 210,
                            ["x"] = 480,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["hidden"] = true,
            },
            [11] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WGroupCW",
                        ["name"] = "WGroupCW<1>",
                        ["geom"] = {
                            ["y"] = 1,
                            ["x"] = 1,
                            ["w"] = 634,
                            ["h"] = 326,
                        },
                        ["switchto"] = true,
                        ["sizepolicy"] = "full",
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["windowid"] = 8388639,
                                ["checkcode"] = 3,
                                ["sizepolicy"] = "full",
                                ["geom"] = {
                                    ["y"] = 0,
                                    ["x"] = 0,
                                    ["w"] = 634,
                                    ["h"] = 326,
                                },
                                ["level"] = 1,
                            },
                        },
                        ["level"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "wicd",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 551,
                    ["x"] = 959,
                    ["w"] = 636,
                    ["h"] = 328,
                },
                ["level"] = 1,
            },
            [12] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WGroupCW",
                        ["name"] = "WGroupCW<6>",
                        ["geom"] = {
                            ["y"] = 1,
                            ["x"] = 1,
                            ["w"] = 820,
                            ["h"] = 382,
                        },
                        ["switchto"] = true,
                        ["sizepolicy"] = "full",
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["windowid"] = 35651587,
                                ["checkcode"] = 4,
                                ["sizepolicy"] = "full",
                                ["geom"] = {
                                    ["y"] = 0,
                                    ["x"] = 0,
                                    ["w"] = 820,
                                    ["h"] = 382,
                                },
                                ["level"] = 1,
                            },
                        },
                        ["level"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "float",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 464,
                    ["x"] = 759,
                    ["w"] = 822,
                    ["h"] = 384,
                },
                ["level"] = 1,
            },
        },
    },
}

