-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0.0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 1.0,
                                                    ["level"] = 1.0,
                                                    ["windowid"] = 4194313.0,
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["y"] = 0.0,
                                                        ["x"] = 0.0,
                                                        ["w"] = 1916.0,
                                                        ["h"] = 1172.0,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 2.0,
                                                ["x"] = 2.0,
                                                ["w"] = 1916.0,
                                                ["h"] = 1172.0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW",
                                        },
                                    },
                                    ["name"] = "WFrame<11>",
                                },
                            },
                            ["tls"] = 1176.0,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<2>",
                    },
                },
                ["switchto"] = true,
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "term",
            },
            [2] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<4>",
                                },
                            },
                            ["tls"] = 1176.0,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<1>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "web",
            },
            [3] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<12>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "dev",
            },
            [4] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<8>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<3>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "doc",
            },
            [5] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "jetbrains",
            },
            [6] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<5>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<4>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "torrent",
            },
            [7] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<6>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<5>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "wine",
            },
            [8] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<1>",
                                },
                            },
                            ["tls"] = 960.0,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 960.0,
                            ["dir"] = "horizontal",
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<7>",
                                },
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<6>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "vm",
            },
            [9] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<9>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<7>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "steam",
            },
            [10] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<8>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "gimp",
            },
            [11] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<3>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<9>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "media",
            },
            [12] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<10>",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<10>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "admin",
            },
            [13] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "root",
            },
            [14] = {
                ["hidden"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<2>",
                                },
                            },
                            ["tls"] = 1176.0,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<11>",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "unreal",
            },
            [15] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1025.0,
                        ["mode"] = 0.0,
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["y"] = 260.0,
                            ["x"] = 559.0,
                            ["w"] = 1361.0,
                            ["h"] = 744.0,
                        },
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*",
                    },
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                },
                ["type"] = "WGroupWS",
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["name"] = "*scratchws*",
            },
            [16] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 379.0,
                    ["x"] = 489.0,
                    ["w"] = 1021.0,
                    ["h"] = 444.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "ncmpcpp",
            },
            [17] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 51.0,
                    ["w"] = 1804.0,
                    ["h"] = 464.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "console",
            },
            [18] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 1395.0,
                    ["w"] = 525.0,
                    ["h"] = 1149.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "im",
            },
            [19] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 8.0,
                    ["x"] = 23.0,
                    ["w"] = 1864.0,
                    ["h"] = 1148.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "float2",
            },
            [20] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 700.0,
                    ["w"] = 1185.0,
                    ["h"] = 704.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "ranger",
            },
            [21] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 0.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 360.0,
                    ["x"] = 640.0,
                    ["w"] = 640.0,
                    ["h"] = 480.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "alsa",
            },
            [22] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 794.0,
                    ["x"] = 927.0,
                    ["w"] = 972.0,
                    ["h"] = 367.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "gdb",
            },
            [23] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 1050.0,
                    ["x"] = 1748.0,
                    ["w"] = 148.0,
                    ["h"] = 68.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "stalonetray",
            },
            [24] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 37.0,
                    ["x"] = 1063.0,
                    ["w"] = 113.0,
                    ["h"] = 108.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "feh",
            },
            [25] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 360.0,
                    ["x"] = 600.0,
                    ["w"] = 1314.0,
                    ["h"] = 809.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "radare2",
            },
            [26] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 52.0,
                    ["x"] = 60.0,
                    ["w"] = 1794.0,
                    ["h"] = 1066.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "weechat",
            },
            [27] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 83.0,
                    ["w"] = 1732.0,
                    ["h"] = 836.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "mutt",
            },
            [28] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 35.0,
                    ["x"] = 41.0,
                    ["w"] = 882.0,
                    ["h"] = 656.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "_webcam_",
            },
            [29] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 688.0,
                    ["x"] = 1198.0,
                    ["w"] = 720.0,
                    ["h"] = 480.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "float",
            },
            [30] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 536.0,
                    ["x"] = 347.0,
                    ["w"] = 1510.0,
                    ["h"] = 634.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "nicotine",
            },
            [31] = {
                ["unnumbered"] = true,
                ["level"] = 1.0,
                ["managed"] = {
                },
                ["mode"] = 2.0,
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 63.0,
                    ["w"] = 1794.0,
                    ["h"] = 840.0,
                },
                ["sizepolicy"] = "free",
                ["name"] = "firefox-dialog",
            },
        },
        ["name"] = "WRootWin",
    },
}

