-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["name"] = "WRootWin",
        ["type"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["name"] = "term",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<2>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<11>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["name"] = "WGroupCW",
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["h"] = 1172.0,
                                                ["w"] = 1916.0,
                                                ["x"] = 2.0,
                                                ["y"] = 2.0,
                                            },
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["h"] = 1172.0,
                                                        ["w"] = 1916.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                    },
                                                    ["checkcode"] = 1.0,
                                                    ["windowid"] = 4194313.0,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                },
                                            },
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["tls"] = 1176.0,
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [2] = {
                ["name"] = "web",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<1>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<4>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["name"] = "WGroupCW<1>",
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["h"] = 1172.0,
                                                ["w"] = 1916.0,
                                                ["x"] = 2.0,
                                                ["y"] = 2.0,
                                            },
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["h"] = 1172.0,
                                                        ["w"] = 1916.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                    },
                                                    ["checkcode"] = 2.0,
                                                    ["windowid"] = 52428834.0,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                },
                                            },
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["tls"] = 1176.0,
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [3] = {
                ["name"] = "dev",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<2>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["name"] = "WGroupCW<2>",
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["h"] = 1172.0,
                                                ["w"] = 1916.0,
                                                ["x"] = 2.0,
                                                ["y"] = 2.0,
                                            },
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["h"] = 1150.0,
                                                        ["w"] = 1910.0,
                                                        ["x"] = 3.0,
                                                        ["y"] = 11.0,
                                                    },
                                                    ["checkcode"] = 3.0,
                                                    ["windowid"] = 46137346.0,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                },
                                            },
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["tls"] = 1176.0,
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [4] = {
                ["name"] = "doc",
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<3>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<8>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["name"] = "WGroupCW<3>",
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["h"] = 1172.0,
                                                ["w"] = 1916.0,
                                                ["x"] = 2.0,
                                                ["y"] = 2.0,
                                            },
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["h"] = 1172.0,
                                                        ["w"] = 1916.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                    },
                                                    ["checkcode"] = 4.0,
                                                    ["windowid"] = 56623107.0,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                },
                                            },
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 24.0,
                            ["dir"] = "vertical",
                            ["tls"] = 1176.0,
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [5] = {
                ["name"] = "jetbrains",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                },
            },
            [6] = {
                ["name"] = "torrent",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<4>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["name"] = "WFrame<5>",
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                    [1] = {
                                        ["name"] = "WGroupCW<5>",
                                        ["type"] = "WGroupCW",
                                        ["level"] = 0.0,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["h"] = 1196.0,
                                            ["w"] = 1916.0,
                                            ["x"] = 2.0,
                                            ["y"] = 2.0,
                                        },
                                        ["switchto"] = true,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["h"] = 1196.0,
                                                    ["w"] = 1916.0,
                                                    ["x"] = 0.0,
                                                    ["y"] = 0.0,
                                                },
                                                ["checkcode"] = 5.0,
                                                ["windowid"] = 54526003.0,
                                                ["sizepolicy"] = "full",
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["level"] = 1.0,
                                            },
                                        },
                                    },
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [7] = {
                ["name"] = "wine",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<5>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["name"] = "WFrame<6>",
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [8] = {
                ["name"] = "vm",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<6>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["br"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<7>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["name"] = "WFrame<1>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2.0,
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 960.0,
                            ["dir"] = "horizontal",
                            ["tls"] = 960.0,
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [9] = {
                ["name"] = "steam",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<7>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["name"] = "WFrame<9>",
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [10] = {
                ["name"] = "gimp",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<8>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["name"] = "WFrame",
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [11] = {
                ["name"] = "media",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<9>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["name"] = "WFrame<3>",
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [12] = {
                ["name"] = "admin",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                    [1] = {
                        ["name"] = "WTiling<10>",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["name"] = "WFrame<10>",
                                ["type"] = "WFrame",
                                ["mode"] = 2.0,
                                ["managed"] = {
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1200.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                        },
                    },
                },
            },
            [13] = {
                ["name"] = "root",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["managed"] = {
                },
            },
            [14] = {
                ["name"] = "*scratchws*",
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["h"] = 744.0,
                            ["w"] = 1361.0,
                            ["x"] = 559.0,
                            ["y"] = 260.0,
                        },
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["level"] = 1025.0,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*",
                        ["mode"] = 0.0,
                        ["managed"] = {
                        },
                    },
                },
                ["geom"] = {
                    ["h"] = 1200.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "full",
                ["unnumbered"] = true,
            },
            [15] = {
                ["name"] = "ncmpcpp",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                    [1] = {
                        ["name"] = "WGroupCW<6>",
                        ["type"] = "WGroupCW",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["h"] = 440.0,
                            ["w"] = 1017.0,
                            ["x"] = 2.0,
                            ["y"] = 2.0,
                        },
                        ["switchto"] = true,
                        ["managed"] = {
                            [1] = {
                                ["geom"] = {
                                    ["h"] = 440.0,
                                    ["w"] = 1017.0,
                                    ["x"] = 0.0,
                                    ["y"] = 0.0,
                                },
                                ["checkcode"] = 6.0,
                                ["windowid"] = 48234497.0,
                                ["sizepolicy"] = "full",
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["level"] = 1.0,
                            },
                        },
                    },
                },
                ["geom"] = {
                    ["h"] = 444.0,
                    ["w"] = 1021.0,
                    ["x"] = 489.0,
                    ["y"] = 379.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [16] = {
                ["name"] = "console",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 277.0,
                    ["w"] = 1822.0,
                    ["x"] = 48.0,
                    ["y"] = 36.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [17] = {
                ["name"] = "im",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                    [1] = {
                        ["name"] = "WGroupCW<7>",
                        ["type"] = "WGroupCW",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["h"] = 1145.0,
                            ["w"] = 521.0,
                            ["x"] = 2.0,
                            ["y"] = 2.0,
                        },
                        ["switchto"] = true,
                        ["managed"] = {
                            [1] = {
                                ["geom"] = {
                                    ["h"] = 1145.0,
                                    ["w"] = 521.0,
                                    ["x"] = 0.0,
                                    ["y"] = 0.0,
                                },
                                ["checkcode"] = 7.0,
                                ["windowid"] = 79691816.0,
                                ["sizepolicy"] = "full",
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["level"] = 1.0,
                            },
                        },
                    },
                },
                ["geom"] = {
                    ["h"] = 1149.0,
                    ["w"] = 525.0,
                    ["x"] = 1391.0,
                    ["y"] = 0.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [18] = {
                ["name"] = "float2",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 1148.0,
                    ["w"] = 1864.0,
                    ["x"] = 23.0,
                    ["y"] = 8.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [19] = {
                ["name"] = "ranger",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 704.0,
                    ["w"] = 1185.0,
                    ["x"] = 700.0,
                    ["y"] = 0.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [20] = {
                ["name"] = "alsa",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 480.0,
                    ["w"] = 640.0,
                    ["x"] = 640.0,
                    ["y"] = 360.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 0.0,
                ["unnumbered"] = true,
            },
            [21] = {
                ["name"] = "gdb",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 367.0,
                    ["w"] = 972.0,
                    ["x"] = 927.0,
                    ["y"] = 794.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [22] = {
                ["name"] = "stalonetray",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                    [1] = {
                        ["name"] = "WGroupCW<8>",
                        ["type"] = "WGroupCW",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["h"] = 64.0,
                            ["w"] = 144.0,
                            ["x"] = 2.0,
                            ["y"] = 2.0,
                        },
                        ["switchto"] = true,
                        ["managed"] = {
                            [1] = {
                                ["geom"] = {
                                    ["h"] = 16.0,
                                    ["w"] = 32.0,
                                    ["x"] = 56.0,
                                    ["y"] = 24.0,
                                },
                                ["checkcode"] = 8.0,
                                ["windowid"] = 16777217.0,
                                ["sizepolicy"] = "full",
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["level"] = 1.0,
                            },
                        },
                    },
                },
                ["geom"] = {
                    ["h"] = 68.0,
                    ["w"] = 148.0,
                    ["x"] = 1748.0,
                    ["y"] = 1050.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [23] = {
                ["name"] = "feh",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 108.0,
                    ["w"] = 113.0,
                    ["x"] = 1063.0,
                    ["y"] = 37.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [24] = {
                ["name"] = "radare2",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 809.0,
                    ["w"] = 1314.0,
                    ["x"] = 600.0,
                    ["y"] = 360.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [25] = {
                ["name"] = "weechat",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                },
                ["geom"] = {
                    ["h"] = 1066.0,
                    ["w"] = 1794.0,
                    ["x"] = 60.0,
                    ["y"] = 52.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
            [26] = {
                ["name"] = "mutt",
                ["hidden"] = true,
                ["type"] = "WFrame",
                ["managed"] = {
                    [1] = {
                        ["name"] = "WGroupCW<4>",
                        ["type"] = "WGroupCW",
                        ["level"] = 0.0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["h"] = 806.0,
                            ["w"] = 1836.0,
                            ["x"] = 2.0,
                            ["y"] = 2.0,
                        },
                        ["switchto"] = true,
                        ["managed"] = {
                            [1] = {
                                ["geom"] = {
                                    ["h"] = 806.0,
                                    ["w"] = 1836.0,
                                    ["x"] = 0.0,
                                    ["y"] = 0.0,
                                },
                                ["checkcode"] = 9.0,
                                ["windowid"] = 41943042.0,
                                ["sizepolicy"] = "full",
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["level"] = 1.0,
                            },
                        },
                    },
                },
                ["geom"] = {
                    ["h"] = 810.0,
                    ["w"] = 1840.0,
                    ["x"] = 36.0,
                    ["y"] = 26.0,
                },
                ["level"] = 1.0,
                ["sizepolicy"] = "free",
                ["mode"] = 2.0,
                ["unnumbered"] = true,
            },
        },
    },
}

