-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [7] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "ncmpcpp",
                ["level"] = 1,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 360,
                    ["x"] = 478,
                    ["w"] = 1030,
                    ["h"] = 464,
                },
                ["hidden"] = true,
            },
            [1] = {
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["name"] = "term",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1200,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1176,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["level"] = 0,
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["geom"] = {
                                                ["y"] = 2,
                                                ["x"] = 2,
                                                ["w"] = 1916,
                                                ["h"] = 1172,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1916,
                                                        ["h"] = 1172,
                                                    },
                                                    ["windowid"] = 10485769,
                                                },
                                            },
                                        },
                                    },
                                    ["mode"] = 2,
                                    ["name"] = "main_terminal",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 24,
                        },
                    },
                },
            },
            [2] = {
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["name"] = "web",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1200,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1176,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["mode"] = 2,
                                    ["name"] = "WFrame",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 24,
                        },
                    },
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
            },
            [4] = {
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["name"] = "doc",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1200,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["mode"] = 2,
                                ["name"] = "WFrame<1>",
                                ["type"] = "WFrame",
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
            },
            [8] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "console",
                ["level"] = 1,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 64,
                    ["w"] = 1808,
                    ["h"] = 368,
                },
                ["hidden"] = true,
            },
            [9] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "im",
                ["level"] = 1,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 1424,
                    ["w"] = 495,
                    ["h"] = 1149,
                },
                ["hidden"] = true,
            },
            [5] = {
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["name"] = "jetbrains",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<4>",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1200,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1176,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<3>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 24,
                        },
                    },
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
            },
            [10] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "float2",
                ["level"] = 1,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 640,
                    ["w"] = 1280,
                    ["h"] = 834,
                },
                ["hidden"] = true,
            },
            [3] = {
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["name"] = "dev",
                ["initial_outputs"] = {
                    [1] = "DVI-I-1",
                },
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1200,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1176,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["mode"] = 2,
                                    ["name"] = "wim",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 24,
                        },
                    },
                },
                ["sizepolicy"] = "full",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
            },
            [6] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["level"] = 1025,
                        ["geom"] = {
                            ["y"] = 260,
                            ["x"] = 559,
                            ["w"] = 1361,
                            ["h"] = 744,
                        },
                        ["mode"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1200,
                },
                ["level"] = 1,
            },
            [11] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "ranger",
                ["level"] = 1,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 700,
                    ["w"] = 1216,
                    ["h"] = 764,
                },
                ["hidden"] = true,
            },
        },
    },
}

