#!/bin/zsh

C0="$(xrq '*color0')"
C1="$(xrq '*color1')"
C2="$(xrq '*color2')"
C3="$(xrq '*color3')"
C4="$(xrq '*color4')"
C5="$(xrq '*color5')"
C6="$(xrq '*color6')"
C7="$(xrq '*color7')"
C8="$(xrq '*color8')"
C9="$(xrq '*color9')"
C10="$(xrq '*color10')"
C11="$(xrq '*color11')"
C12="$(xrq '*color12')"
C13="$(xrq '*color13')"
C14="$(xrq '*color14')"
C15="$(xrq '*color15')"
CFG="$(xrq '*foreground')"
CBG="$(xrq '*.background')"

source ${XDG_CONFIG_HOME}/xinit/hotkeys.zsh
sxhkd -c "${XDG_CONFIG_HOME}/herbstluftwm/sxhkd/sxhkd.conf" &

function _hc() { ex=(${ex} , ${@}) }

Mod=Mod4

TAG_NAMES=( 0x0 0x1 0x2 0x3 0x4 0x5 0x6 0x7 0x8 0x9 0xA )
TAG_BINDS=( {1..10} )

herbstclient chain , \
    emit_hook reload ,\
    keyunbind --all , \
    mouseunbind --all , \
    unsetenv HCT , \
    set default_frame_layout 2 , \
    load default '(clients max:0)' , \
    rename default "${TAG_NAMES[1]}"

for ((i=1; i<$((${TAG_BINDS[-1]}+1)); i++)) ; do
  if [[ $i -gt ${TAG_BINDS[1]} ]] { herbstclient add ${TAG_NAMES[$i]} }
  herbstclient and , keybind $Mod-${i[-1]} use ${TAG_NAMES[$i]} , keybind $Mod-Shift-${i[-1]} move ${TAG_NAMES[$i]}
done

_hc mousebind $Mod-B1 move
_hc mousebind $Mod-B2 zoom
_hc mousebind $Mod-B3 resize

_hc set focus_stealing_prevention 0
_hc set focus_follows_mouse 0
_hc set raise_on_focus 0
_hc set raise_on_click 1
_hc set mouse_recenter_gap 0
_hc set always_show_frame 1
_hc set frame_bg_transparent 1
_hc set frame_transparent_width 0
_hc set frame_border_width 2
_hc set window_border_width 5
_hc set window_border_inner_width 0
_hc set gapless_grid 0
_hc set frame_gap -2
_hc set window_gap -2
_hc set frame_padding 2
_hc set smart_window_surroundings 0
_hc set smart_frame_surroundings 0
_hc set frame_border_active_color '#101010'
_hc set frame_border_normal_color '#101010'
_hc set frame_bg_active_color '#000000'
_hc set frame_bg_normal_color '#000000'

_hc set window_border_active_color '#1f3b4f'
_hc set window_border_normal_color '#161616'
_hc set window_border_urgent_color '#4cdcd4'
_hc set tree_style '╾│ ├└╼─┐'
_hc detect_monitors
_hc pad 10 0 10 10 10

_hc unrule -F
_hc rule focus=on

_hc rule class=Firefox tag=VⅡ
_hc rule class=Dwb tag=VⅢ
_hc rule class=Gimp tag=ⅠⅩ
_hc rule class=Pavucontrol tag=Ⅹ

_hc rule title="Open Image" pseudotile=on
_hc rule title="Save As" pseudotile=on
_hc rule title="Save file" pseudotile=on
_hc rule title="About Mozilla Firefox" pseudotile=on

_hc rule class=Toplevel pseudotile=on
_hc rule instance=gcolor2 pseudotile=on
_hc rule class=XFontSel pseudotile=on
_hc rule class=lxappearance pseudotile=on
_hc rule class=firefox-dialog pseudotile=on

# defwinprop({instance="mutt",transient_mode="off",target="mutt",scratchpad="true"})
# defwinprop({class="Chromium",transient_mode="off",transient_mode="off",jumpto=true,target="web",tag="www"})
# defwinprop({class="Tor Browser",transient_mode="off",jumpto="on",target="web",tag="www"})
# defwinprop({class="Firefox",transient_mode="off",jumpto="on",target="web",tag="www"})
# defwinprop({class="Firefox",role="Manager",instance="Download",transient_mode="off",jumpto="off",target="firefox-dialog"})
# defwinprop({class="Firefox",instance="Dialog",float=true})
# defwinprop({class="Firefox",role="Organizer",target="firefox-dialog"})
# defwinprop({class="Firefox",role="GtkFileChooserDialog",
# defwinprop({class="Conkeror",instance="Navigator",transient_mode="off",target="web",tag="www"})
# defwinprop({class="Iceweasel",role="www",transient_mode="off",jumpto="on",target="web",tag="www"})
# defwinprop({class="Icecat",role="www",transient_mode="off",jumpto="on",target="web",tag="www"})
# defwinprop({class="Navigator",role="www",transient_mode="off",jumpto="on",target="web",tag="www"})
# defwinprop({class="Vimprobable2",role="vimprobable2",transient_mode="off",jumpto="on",target="web",tag="www"})
# -------------------------------------[[ IM ]]---------------------------------------
# defwinprop({instance="kopete",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({instance="skype",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({class="ViberPC",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({class="Telegram",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({class="telegram",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({class="telegram-desktop",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({name="Telegram",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({instance="finch",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({instance="centerim",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({instance="centerim",jumpto=false,winlist_ignore=true,transient_mode="off",target="im",scratchpad="true"})
# defwinprop({instance="weechat-curses",jumpto=false,winlist_ignore=true,transient_mode="off",target="chat",scratchpad="true"})
# defwinprop({instance="_weechat_",jumpto=false,winlist_ignore=true,transient_mode="off",target="weechat",scratchpad="true"})
# -------------------------------------[[ DOC ]]---------------------------------------
# defwinprop({class="Okular",instance="okular",transient_mode="off",jumpto=true,target="doc", tag="pdf"})
# defwinprop({name="Open Document*",class="Okular",instance="okular",transient_mode="off",jumpto=true,target="doc",float=true})
# defwinprop({class="Apvlv",instance="apvlv",transient_mode="off",jumpto=true,target="doc",tag="pdf"})
# defwinprop({class="Zathura",instance="zathura",transient_mode="off",jumpto=true,target="doc",tag="pdf"})
# defwinprop({class="Xpdf",instance="openDialog_popup",ignore_cfgrq=true,tag="pdf"})
# defwinprop({class="Evince",instance="evince",transient_mode="off",jumpto=true,target="doc",tag="pdf"})
# defwinprop({class="XDvi",target="doc",tag="pdf"})
# defwinprop({class="libreoffice*",instance="*",target="doc",tag="writer"})
# defwinprop({class="abiword",instance="*",target="doc",tag="writer"})
# defwinprop({class="atril",instance="*",target="doc",tag="writer"})
# defwinprop({class="guncharmap",instance="*",target="doc",tag="writer"})
# defwinprop({class="Cr3",instance="cr3",target="doc",tag="reader"})
# -------------------------------------[[ MEDIA ]]---------------------------------------
# defwinprop({class="gmpc",target="media"})
# defwinprop({class="MPlayer",jumpto=true,transient_mode="off",target="media",tag="video"})
# defwinprop({class="mplayer2",jumpto=true,transient_mode="off",target="media",tag="video"})
# defwinprop({class="mpv",jumpto=true,transient_mode="off", target="media",tag="video"})
# defwinprop({class="mpv",instance="webcam_mpv",target="_webcam_"})
# defwinprop({class="feh",float=true,ignore_cfgrq=true,transient_mode="current"})
# defwinprop({class="qiv",jumpto="on",transient_mode="normal",float=true})
# defwinprop({class="cheese",target="media",jumpto=true,transient_mode="off",float=false})
# defwinprop({class="spotify",target="ncmpcpp"})
# -------------------------------------[[ DEV ]]--------------------------------------
# defwinprop({class="Gvim",instance="gvim",target="dev",jumpto=true,transient_mode="off",userpos=true,
# tag="editor", ignore_max_size=true,ignore_min_size=true,ignore_aspect=true,ignore_resizeinc=true })
# defwinprop({class="Atom",target="dev",jumpto=true,transient_mode="off",tag="aeditor"})
# defwinprop({instance="subl3|sublime_text",target="dev",jumpto=true,transient_mode="off",userpos=true, tag="editor" })
# defwinprop({class="URxvt",instance="wim",target="dev",jumpto=true,transient_mode="off",
# tag="editor",transparent=false
# -- ignore_max_size=true, ignore_min_size=true,ignore_resizeinc=true,
# })
# defwinprop({class="wim",target="dev",jumpto=true,transient_mode="off", tag="editor",transparent=false})
# defwinprop({class="nwim",target="dev",jumpto=true,transient_mode="off", tag="editor",transparent=false})
# defwinprop({class="Qvim",instance="qvim",target="dev",jumpto=true,transient_mode="off",
# ignore_max_size=false,ignore_min_size=false,ignore_aspect=false,ignore_resizeinc=true,
# tag="editor"
# })
# defwinprop({class="Emacs",instance="emacs",target="dev",lazyresize=true,jumpto=true, tag="geditor"})
# defwinprop({class="Emacs",instance="emacs",name="Question",float=true, tag="geditor"})
# defwinprop({class="com-sun-javaws-Main",instance="sun-awt-X11-XFramePeer",target="topcoder"})
# -----------------------------------[[ IDEA ]]--------------------------------------
# defwinprop({class="jetbrains-idea",instance="*",target="jetbrains",floating=true,tag="ide",jumpto=true})
# defwinprop({class="jetbrains-idea-ce",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,tag="ide",jumpto=true})
# defwinprop({class="jetbrains-idea",instance="sun-awt-X11-XWindowPeer",target="jetbrains",floating=true,tag="ide",jumpto=true})
# defwinprop({class="jetbrains-idea",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,tag="ide",jumpto=true})
# defwinprop({class="jetbrains-idea",instance="sun-awt-X11-XFramePeer",target="jetbrains",floating=true,transient_mode="off",tag="ide",jumpto=true})
# ----------------------------------[[ WEBSTORM ]]-----------------------------------
# defwinprop({class="jetbrains-webstorm",instance="*",target="jetbrains",target="jetbrains",floating=true,transient_mode="current",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-webstorm-ce",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,transient_mode="current",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-webstorm",instance="sun-awt-X11-XWindowPeer",target="jetbrains",floating=true,transient_mode="current",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-webstorm",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,transient_mode="current",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-webstorm",instance="sun-awt-X11-XFramePeer",target="jetbrains",floating=true,transient_mode="off",tag="ide",jumpto=true})
# ----------------------------------[[  CLION   ]]-----------------------------------
# defwinprop({class="jetbrains-clion",instance="*",target="jetbrains",target="jetbrains",floating=true,transient_mode="current",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-clion",instance="sun-awt-X11-XWindowPeer",target="jetbrains",floating=true,transient_mode="current",target="jetbrains",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-clion",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,transient_mode="current",target="jetbrains",tag="ide",jumpto=true})
# defwinprop({class="jetbrains-clion",instance="sun-awt-X11-XFramePeer",target="jetbrains",floating=true,transient_mode="off",target="jetbrains",tag="ide",jumpto=true})
# -------------------------------[[ ANDROID STUDIO ]]--------------------------------
# defwinprop({class="jetbrains-android-studio",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,transient_mode="current", tag="ide",jumpto=true})
# defwinprop({class="jetbrains-android-studio",instance="sun-awt-X11-XWindowPeer",target="jetbrains",floating=true,transient_mode="current", tag="ide",jumpto=true})
# defwinprop({class="jetbrains-android-studio",instance="sun-awt-X11-XDialogPeer",target="jetbrains",floating=true,transient_mode="current", tag="ide",jumpto=true})
# defwinprop({class="jetbrains-android-studio",instance="sun-awt-X11-XFramePeer",target="jetbrains",floating=true,transient_mode="off", tag="ide",jumpto=true})
# -------------------------------------[[ VM ]]--------------------------------------
# defwinprop({class="vmware",instance="Vmware",target="vm",jumpto=true,transient_mode="off",float=true,tag="virt"})
# defwinprop({class="VirtualBox",jumpto=true,target="vm",transient_mode="off",tag="virt"})
# defwinprop({class="Vmware",jumpto=true,target="vm",transient_mode="on",tag="virt"})
# defwinprop({class="QEMU",jumpto=true,target="vm",transient_mode="on",tag="virt"})
# defwinprop({instance="qemu-system-x86_64",jumpto=true,target="vm",transient_mode="on",tag="virt"})
# defwinprop({class="spicec",instance="spicec",jumpto=true,target="vm",transient_mode="on",tag="virt"})
# defwinprop({instance="spicy",jumpto=true,target="vm",transient_mode="on",tag="virt"})
# -------------------------------------[[   GRARPHIC  ]]-----------------------------
# defwinprop({class="inkscape",target="graphic",tag="graph"})
# defwinprop({class="simple-scan",target="graph"})
# defwinprop({class="gthumb",target="graph"})
# defwinprop({class="Gimp",target="gimp",jumpto=true,tag="graph",transient_mode="current"})
# defwinprop({class="Gimp",target="gimp",jumpto=true,role="gimp-file-open",transient_mode="off",float=true,tag="graph"})
# defwinprop({class="Gimp",target="gimp",jumpto=true,role="gimp-file-save",transient_mode="off",float=true,tag="graph"})
# defwinprop({class="Gimp",target="gimp",jumpto=true,role="gimp-message-dialog",transient_mode="off",float=true,tag="graph"})
# defwinprop({class="Gimp",target="gimp",jumpto=true,role="gimp-image-new",transient_mode="off",float=true,tag="graph"})
# defwinprop({class="Gimp",target="gimp",jumpto=true,role="gimp-toolbox-color-dialog",transient_mode="off",float=true,tag="graph"})
# -------------------------------------[[ TRAY'n'DOCK ]]------------------------------
# defwinprop({class="stalonetray",instance="stalonetray",statusbar="*",float=true,target="stalonetray"})
# defwinprop({is_dockapp=true,statusbar="*",float=true})
# -------------------------------------[[   ADMIN  ]]---------------------------------
# defwinprop({instance="_logs_",target="admin",jumpto=true,tag="admin"})
# defwinprop({instance="remmina",target="admin",jumpto=true,tag="admin"})
# defwinprop({instance="htop_term",target="admin",jumpto=true,tag="admin"})
# defwinprop({instance="glances_term",target="admin",jumpto=true,tag="admin"})
# defwinprop({instance="gparted",target="admin",jumpto=true,tag="admin"})
# defwinprop({instance="gnome-disks",target="admin",jumpto=true,tag="admin"})
# defwinprop({instance="seahorse",target="admin",jumpto=true,tag="admin"})
# -------------------------------------[[  wine / games  ]]---------------------------
# defwinprop({class="Crossover",target="wine",jumpto=true,tag="virt",float=true})
# defwinprop({class="Wine",target="wine",jumpto=true,tag="virt"})
# defwinprop({name="wine.*",target="wine",jumpto=true,tag="virt"})
# defwinprop({name="explorer.exe",target="wine",jumpto=true,tag="virt"})
# defwinprop({name="Explorer.exe",target="wine",jumpto=true,tag="virt"})
# defwinprop({class="explorer.exe",target="wine",jumpto=true,tag="virt"})
# defwinprop({class="Explorer.exe",target="wine",jumpto=true,tag="virt"})
# defwinprop({class="steam",target="wine",jumpto=true,tag="virt",float=true})
# defwinprop({class="Steam",target="wine",jumpto=true,tag="virt"})
# defwinprop({class="dota2",target="wine",jumpto=true,float=true,tag="virt"})
# defwinprop({class="darkest.bin.x86_64",target="wine",jumpto=true,float=true,tag="virt"})
# -------------------------------------[[ TORRENT ]]-----------------------------------
# defwinprop({class="Ktorrent",winlist_ignore=true,transient_mode="off",instance="ktorrent",target="torrent",tag="torrent"})
# defwinprop({class="Vuze",winlist_ignore=true,transient_mode="off",target="torrent",tag="torrent",jumpto=true,float=false})
# defwinprop({class="Vuze",is_transient=true,winlist_ignore=true,transient_mode="off",target="torrent",tag="torrent",jumpto=true,float=true})
# -------------------------------------[[  ETC  ]]-------------------------------------
# defwinprop({class="UE4Editor",floating=true,transient_mode="off",target="unreal",tag="unreal"})
# defwinprop({class="Xfce",float=true})
# defwinprop({class="Xmessage",float=true})
# defwinprop({class="com-sun-javaws-Main",float=true})
# defwinprop({instance="recoll",jumpto=false,winlist_ignore=true,target="search"})
# defwinprop({instance="stardict",jumpto=true,winlist_ignore=true,transient_mode="off",winlist_ignore=true,target="float",scratchpad="true"})
# defwinprop({instance="lxappearance",jumpto=true,winlist_ignore=true,transient_mode="off",winlist_ignore=true,target="float",scratchpad="true"})
# defwinprop({class="rdesktop",instance="rdesktop",transient_mode="off",jumpto=true,target="rdesktop"})
# defwinprop({class="Conky",winlist_ignore=true,float=true})
# defwinprop({instance="mpd-pad2",winlist_ignore=true,transient_mode="off",target="ncmpcpp",scratchpad="true"})
# defwinprop({class="cool-retro-term",winlist_ignore=true,transient_mode="off",target="ncmpcpp",scratchpad="true"})
# defwinprop({class="Tilda",instance="tilda",winlist_ignore=true,transient_mode="off",float=true})
# defwinprop({class="Guake",instance="guake",winlist_ignore=true,transient_mode="off",float=true})
# defwinprop({class="Pavucontrol",instance="pavucontrol",winlist_ignore=true,transient_mode="off",target="float",scratchpad="true"})
# defwinprop({instance="wicd",winlist_ignore=true,transient_mode="off",target="wicd",scratchpad="true"})
# defwinprop({instance="ranger",winlist_ignore=true,transient_mode="off",target="ranger",scrachpad=true})
# defwinprop({class="ranger",winlist_ignore=true,transient_mode="off",target="ranger",scrachpad=true})
# defwinprop({class="caja",winlist_ignore=true,transient_mode="off",target="ranger",scratchpad="true"})
# defwinprop({instance="console",winlist_ignore=true,transient_mode="off",target="console",scratchpad="true"})
# defwinprop({instance="gdb",winlist_ignore=true,transient_mode="off",target="gdb",scratchpad="true"})
# defwinprop({instance="mixer",winlist_ignore=true,transient_mode="off",target="alsa",scratchpad="true"})
# defwinprop({instance="htop",winlist_ignore=true,transient_mode="off",target="top",scratchpad="true"})
# defwinprop({instance="gcolor2",winlist_ignore=true,transient_mode="off",jumpto=true,target="float",scratchpad="true"})
# defwinprop({instance="gpick",winlist_ignore=true,transient_mode="off",jumpto=true,target="float",scratchpad="true"})
# defwinprop({class="Nicotine",instance="nicotine",transient_mode="off",target="nicotine",tag="soulseek",scratchpad="true"})
# defwinprop({class="Nicotine.py",instance="nicotine.py",transient_mode="off",target="nicotine",tag="soulseek",scratchpad="true"})
# defwinprop({class="Nicotine.py",instance="nicotine.py",transient_mode="off",target="nicotine",tag="soulseek",scratchpad="true"})

_hc rule class=tint2 manage=off focus=off
_hc rule class=tint2 manage=off focus=off

_hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
_hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
_hc rule windowtype~'_NET_WM_WINDOW_TYPE_(FULLSCREEN|FS)' fullscreen=on


_hc spawn ${XDG_CONFIG_DIR}/herbstluftwm/dzen-post.zsh
_hc emit_hook complete

_hc set_layout max
_hc rename default "${tag_names[0]}" || true

herbstclient chain ${ex} &

_hc unlock
