#!/bin/zsh

C0="$(xrq '*color0')"
C1="$(xrq '*color1')"
C2="$(xrq '*color2')"
C3="$(xrq '*color3')"
C4="$(xrq '*color4')"
C5="$(xrq '*color5')"
C6="$(xrq '*color6')"
C7="$(xrq '*color7')"
C8="$(xrq '*color8')"
C9="$(xrq '*color9')"
C10="$(xrq '*color10')"
C11="$(xrq '*color11')"
C12="$(xrq '*color12')"
C13="$(xrq '*color13')"
C14="$(xrq '*color14')"
C15="$(xrq '*color15')"
CFG="$(xrq '*foreground')"
CBG="$(xrq '*.background')"

source ${XDG_CONFIG_HOME}/xinit/hotkeys.zsh
sxhkd -c "${XDG_CONFIG_HOME}/herbstluftwm/sxhkd/sxhkd.conf" &

function _hc() { ex=(${ex} , ${@}) }

Mod=Mod4

TAG_NAMES=( 0x0 0x1 0x2 0x3 0x4 0x5 0x6 0x7 0x8 0x9 0xA )
TAG_BINDS=( {1..10} )

herbstclient chain , \
    emit_hook reload ,\
    keyunbind --all , \
    mouseunbind --all , \
    unsetenv HCT , \
    set default_frame_layout 2 , \
    load default '(clients max:0)' , \
    rename default "${TAG_NAMES[1]}"

for ((i=1; i<$((${TAG_BINDS[-1]}+1)); i++)) ; do
  if [[ $i -gt ${TAG_BINDS[1]} ]] { herbstclient add ${TAG_NAMES[$i]} }
  herbstclient and , keybind $Mod-${i[-1]} use ${TAG_NAMES[$i]} , keybind $Mod-Shift-${i[-1]} move ${TAG_NAMES[$i]}
done

_hc mousebind $Mod-Button1 move
_hc mousebind $Mod-Button2 zoom
_hc mousebind $Mod-Button3 resize

_hc set focus_stealing_prevention 0
_hc set focus_follows_mouse 0
_hc set raise_on_focus 0
_hc set raise_on_click 1
_hc set mouse_recenter_gap 0
_hc set always_show_frame 1
_hc set frame_bg_transparent 1
_hc set frame_transparent_width 0
_hc set frame_border_width 2
_hc set window_border_width 5
_hc set window_border_inner_width 0
_hc set gapless_grid 0
_hc set frame_gap -2
_hc set window_gap -2
_hc set frame_padding 2
_hc set smart_window_surroundings 0
_hc set smart_frame_surroundings 0
_hc set frame_border_active_color '#101010'
_hc set frame_border_normal_color '#101010'
_hc set frame_bg_active_color '#000000'
_hc set frame_bg_normal_color '#000000'

_hc set window_border_active_color '#1f3b4f'
_hc set window_border_normal_color '#161616'
_hc set window_border_urgent_color '#4cdcd4'
_hc set tree_style '╾│ ├└╼─┐'
_hc detect_monitors
_hc pad 10 0 10 10 10

_hc unrule -F
_hc rule focus=on

_hc rule class=Firefox tag=VⅡ
_hc rule class=Dwb tag=VⅢ
_hc rule class=Gimp tag=ⅠⅩ
_hc rule class=Pavucontrol tag=Ⅹ

_hc rule title="Open Image" pseudotile=on
_hc rule title="Save As" pseudotile=on
_hc rule title="Save file" pseudotile=on
_hc rule title="About Mozilla Firefox" pseudotile=on
_hc rule class=Toplevel pseudotile=on
_hc rule instance=gcolor2 pseudotile=on
_hc rule class=XFontSel pseudotile=on
_hc rule class=tint2 manage=off focus=off
_hc rule class=tint2 manage=off focus=off
_hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
_hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
_hc rule windowtype~'_NET_WM_WINDOW_TYPE_(FULLSCREEN|FS)' fullscreen=on


_hc spawn ${XDG_CONFIG_DIR}/herbstluftwm/dzen-post.zsh
_hc emit_hook complete

_hc set_layout max
_hc rename default "${tag_names[0]}" || true

herbstclient chain ${ex} &

_hc unlock
