-- This file has been generated by notion. Do not edit.
return {
    ["date"] = {
        ["date_format"] = "[ %H:%M ]",
    },
    ["exec"] = {
        ["xkb"] = {
            ["program"] = "~/bin/0xE-mon/klay.sh",
            ["retry_delay"] = 300,
        },
        ["kt"] = {
            ["program"] = "~/bin/0xE-mon/crntsng.sh",
            ["retry_delay"] = 1000,
        },
        ["mounted"] = {
            ["program"] = "~/bin/0xE-mon/mounts.sh",
            ["retry_delay"] = 2000,
        },
    },
}

