-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["tls"] = 878,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 2,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<1>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 1,
                                                ["x"] = 1,
                                                ["w"] = 1598,
                                                ["h"] = 876,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 12582921,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1598,
                                                        ["h"] = 876,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 22,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 210,
                            ["x"] = 480,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["hidden"] = true,
            },
            [3] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WGroupCW",
                        ["name"] = "WGroupCW<2>",
                        ["geom"] = {
                            ["y"] = 1,
                            ["x"] = 1,
                            ["w"] = 634,
                            ["h"] = 466,
                        },
                        ["switchto"] = true,
                        ["sizepolicy"] = "full",
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WClientWin",
                                ["bottom"] = true,
                                ["windowid"] = 18874377,
                                ["checkcode"] = 2,
                                ["sizepolicy"] = "full",
                                ["geom"] = {
                                    ["y"] = 0,
                                    ["x"] = 0,
                                    ["w"] = 634,
                                    ["h"] = 466,
                                },
                                ["level"] = 1,
                            },
                        },
                        ["level"] = 0,
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "ncmpcpp",
                ["hidden"] = true,
                ["mode"] = 2,
                ["geom"] = {
                    ["y"] = 210,
                    ["x"] = 480,
                    ["w"] = 636,
                    ["h"] = 468,
                },
                ["level"] = 1,
            },
            [4] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "im",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 210,
                    ["x"] = 480,
                    ["w"] = 640,
                    ["h"] = 480,
                },
                ["level"] = 1,
            },
            [5] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "torrent",
                ["hidden"] = true,
                ["mode"] = 0,
                ["geom"] = {
                    ["y"] = 210,
                    ["x"] = 480,
                    ["w"] = 640,
                    ["h"] = 480,
                },
                ["level"] = 1,
            },
        },
    },
}

