-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [14] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 375,
                    ["x"] = 510,
                    ["w"] = 971,
                    ["h"] = 446,
                },
                ["name"] = "ncmpcpp",
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [1] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["brs"] = 24,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["name"] = "Notion WFrame",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2,
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 876,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<1>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "web",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [3] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<2>",
                                ["type"] = "WFrame",
                                ["mode"] = 2,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<5>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "vm",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [7] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<4>",
                                ["type"] = "WFrame",
                                ["mode"] = 2,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<9>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "wine",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [15] = {
                ["sizepolicy"] = "full_bounds",
                ["unnumbered"] = true,
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                },
                ["name"] = "vm1",
                ["type"] = "WGroupWS",
                ["level"] = 1,
            },
            [16] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 127,
                    ["x"] = 362,
                    ["w"] = 1057,
                    ["h"] = 516,
                },
                ["name"] = "torrent",
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [8] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["brs"] = 24,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 4,
                                                ["x"] = 4,
                                                ["w"] = 1592,
                                                ["h"] = 868,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["windowid"] = 8388615,
                                                    ["type"] = "WClientWin",
                                                    ["geom"] = {
                                                        ["y"] = 12,
                                                        ["x"] = 3,
                                                        ["w"] = 1586,
                                                        ["h"] = 844,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["checkcode"] = 1,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["switchto"] = true,
                                            ["name"] = "WGroupCW",
                                            ["level"] = 0,
                                        },
                                    },
                                    ["name"] = "Notion WFrame<7>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 2,
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 876,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling",
                        ["level"] = 0,
                    },
                },
                ["switchto"] = true,
                ["name"] = "term",
                ["level"] = 0,
            },
            [17] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 426,
                    ["x"] = 703,
                    ["w"] = 897,
                    ["h"] = 441,
                },
                ["name"] = "float",
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [4] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<3>",
                                ["type"] = "WFrame",
                                ["mode"] = 1,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<6>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "mutt",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [9] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<10>",
                                ["type"] = "WFrame",
                                ["mode"] = 2,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<2>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "doc",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [19] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 513,
                    ["x"] = 935,
                    ["w"] = 89,
                    ["h"] = 250,
                },
                ["name"] = "wicd",
                ["saved_x"] = 1012,
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["saved_w"] = 5,
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [20] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 392,
                    ["x"] = 1008,
                    ["w"] = 12,
                    ["h"] = 376,
                },
                ["name"] = "alsa",
                ["saved_x"] = 1011,
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["saved_w"] = 5,
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [10] = {
                ["sizepolicy"] = "full",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["pseudomodal"] = true,
                ["managed"] = {
                },
                ["type"] = "WGroupWS",
                ["level"] = 1,
            },
            [21] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 66,
                    ["x"] = 956,
                    ["w"] = 644,
                    ["h"] = 810,
                },
                ["name"] = "im",
                ["saved_x"] = 1038,
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["saved_w"] = 4,
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [2] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<1>",
                                ["type"] = "WFrame",
                                ["mode"] = 2,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<4>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "dev",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [5] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<5>",
                                ["type"] = "WFrame",
                                ["mode"] = 2,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<7>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "mail",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [11] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 144,
                    ["x"] = 363,
                    ["w"] = 277,
                    ["h"] = 336,
                },
                ["name"] = "info",
                ["mode"] = 0,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [12] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 144,
                    ["x"] = 363,
                    ["w"] = 277,
                    ["h"] = 336,
                },
                ["name"] = "littleterm",
                ["mode"] = 0,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [6] = {
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1600,
                            ["h"] = 900,
                        },
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Notion WFrame<9>",
                                ["type"] = "WFrame",
                                ["mode"] = 2,
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<8>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "weechat",
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
            },
            [13] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 328,
                    ["x"] = 300,
                    ["w"] = 500,
                    ["h"] = 272,
                },
                ["name"] = "top",
                ["saved_x"] = 1009,
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["saved_w"] = 2,
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [22] = {
                ["sizepolicy"] = "free",
                ["unnumbered"] = true,
                ["geom"] = {
                    ["y"] = 132,
                    ["x"] = 396,
                    ["w"] = 628,
                    ["h"] = 628,
                },
                ["name"] = "ranger",
                ["mode"] = 2,
                ["hidden"] = true,
                ["managed"] = {
                },
                ["type"] = "WFrame",
                ["level"] = 1,
            },
            [18] = {
                ["sizepolicy"] = "full_bounds",
                ["unnumbered"] = true,
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1600,
                    ["h"] = 900,
                },
                ["managed"] = {
                },
                ["name"] = "example_groupws",
                ["type"] = "WGroupWS",
                ["level"] = 1,
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

