-- Move all windows on a WIonWS to a single frame and destroy the rest.
--
--collapse={}
--function collapse.move_managed(tgt, src)
--    local l=src:managed_list()
--    for _, m in l do
--        tgt:attach(m)
--    end
--end
--
