#!/usr/bin/env zsh

RED="%{"$'\033[03;31m'"%}"
GREEN="%{"$'\033[03;32m'"%}"
BLACK="%{"$'\033[00m'"%}"
[[ $UID -ne 0 ]] && _neg_promptcolor=$GREEN && _neg_user_token=" >> "
[[ $UID -eq 0 ]] && _neg_promptcolor=$RED && _neg_user_token="# "

#title "neg" "%m:%55<...<%~"
setopt sh_word_split
_neg_dyn_pwd=""
_neg_full_path="$(pwd)"
_neg_tilda_path=${_neg_full_path/$HOME/\~}
# write the home directory as a tilda
[[ $_neg_tilda_path[2,-1] == "/" ]] && _neg_tilda_path=$_neg_tilda_path[2,-1]
# otherwise the first element of split_path would be empty.
_neg_forwards_in_tilda_path=${_neg_tilda_path//[^["\/"]/}
# remove everything that is not a "/".
_neg_number_of_elements_in_tilda_path=$(( $#_neg_forwards_in_tilda_path + 1 ))
# we removed the first forward slash, so we need one more element than the number of slashes.
_neg_saveIFS="$IFS"
IFS="/"
_neg_split_path=(${_neg_tilda_path})
_neg_start_of_loop=1
_neg_end_of_loop=$_neg_number_of_elements_in_tilda_path
for i in {$_neg_start_of_loop..$_neg_end_of_loop}
do
if [[ $i == $_neg_end_of_loop ]]; then
    _neg_to_be_added=$_neg_split_path[i]'/'
    _neg_dyn_pwd=$_neg_dyn_pwd$_neg_to_be_added
else
    _neg_to_be_added=$_neg_split_path[i]
    _neg_to_be_added=$_neg_to_be_added[1,1]'/'
    _neg_dyn_pwd=$_neg_dyn_pwd$_neg_to_be_added
fi
done
unsetopt sh_word_split
IFS=$_neg_saveIFS
# remove the slash in front of $HOME
[[ ${_neg_full_path/$HOME/\~} != $_neg_full_path ]] && _neg_dyn_pwd=${_neg_dyn_pwd/\/~/~}

s1="${_neg_promptcolor}"
s2="[$_neg_dyn_pwd[0,-2]"
# s2="$_neg_dyn_pwd[0,-2]"
s3="] >> %b%k%f"
# s3=${BLACK}$_neg_user_token%b%k%f
_neg_prompt="${s1}${s2}${s3}"
echo $_neg_prompt
