-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["initial_outputs"] = {
                    [1] = "default",
                },
                ["geom"] = {
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                    ["y"] = 0.0,
                },
                ["name"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["brs"] = 24.0,
                            ["tls"] = 1176.0,
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["brs"] = 960.0,
                                ["tls"] = 960.0,
                                ["dir"] = "horizontal",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 2.0,
                                        ["name"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0.0,
                                                ["name"] = "WGroupCW<1>",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1.0,
                                                        ["bottom"] = true,
                                                        ["checkcode"] = 1.0,
                                                        ["windowid"] = 4194313.0,
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["geom"] = {
                                                            ["x"] = 0.0,
                                                            ["w"] = 956.0,
                                                            ["h"] = 1172.0,
                                                            ["y"] = 0.0,
                                                        },
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["x"] = 2.0,
                                                    ["w"] = 956.0,
                                                    ["h"] = 1172.0,
                                                    ["y"] = 2.0,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["type"] = "WGroupCW",
                                                ["switchto"] = true,
                                            },
                                        },
                                    },
                                },
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1.0,
                                        ["name"] = "WFrame<1>",
                                        ["managed"] = {
                                        },
                                    },
                                },
                            },
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling",
                        ["geom"] = {
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1200.0,
                            ["y"] = 0.0,
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                    },
                    [2] = {
                        ["level"] = 1.0,
                        ["mode"] = 3.0,
                        ["name"] = "WFrame<2>",
                        ["managed"] = {
                            [1] = {
                                ["level"] = 0.0,
                                ["name"] = "WGroupCW",
                                ["managed"] = {
                                    [1] = {
                                        ["level"] = 1.0,
                                        ["bottom"] = true,
                                        ["checkcode"] = 2.0,
                                        ["windowid"] = 14680065.0,
                                        ["sizepolicy"] = "full",
                                        ["type"] = "WClientWin",
                                        ["geom"] = {
                                            ["x"] = 0.0,
                                            ["w"] = 16.0,
                                            ["h"] = 16.0,
                                            ["y"] = 0.0,
                                        },
                                    },
                                },
                                ["geom"] = {
                                    ["x"] = 2.0,
                                    ["w"] = 16.0,
                                    ["h"] = 16.0,
                                    ["y"] = 28.0,
                                },
                                ["sizepolicy"] = "full",
                                ["type"] = "WGroupCW",
                                ["switchto"] = true,
                            },
                        },
                        ["sizepolicy"] = "visibility_constrained",
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["x"] = 0.0,
                            ["w"] = 20.0,
                            ["h"] = 46.0,
                            ["y"] = 0.0,
                        },
                    },
                },
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["switchto"] = true,
            },
            [2] = {
                ["level"] = 1.0,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1025.0,
                        ["mode"] = 0.0,
                        ["name"] = "*scratchpad*",
                        ["managed"] = {
                        },
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["geom"] = {
                            ["x"] = 80.0,
                            ["w"] = 1361.0,
                            ["h"] = 744.0,
                            ["y"] = 260.0,
                        },
                    },
                },
                ["sizepolicy"] = "full",
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1200.0,
                    ["y"] = 0.0,
                },
            },
        },
    },
}

