#! /bin/dash

#Choose 0 if your dmenu has no transparency support
dmenu_trans=1

#Foreground color for dmenu/dzen2
nf='#CCCCCC'

#background color for dmenu/dzen2
nb='#000000'

#foreground active color for dmenu/dzen2
sf='#000000'

#background active color for dmenu/dzen2
sb='#CCCCCC'

FONT='-xos4-terminus-medium-r-normal--14-140-72-72-c-80-*-*'

~/bin/scripts/dmenu_clip -l 14 -i -fn "$FONT" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf"
