"if !has("gui_running")
"    set <S-F1>=[1;2P
"    set <S-F2>=[1;2Q
"    set <S-F3>=[1;2R
"    set <S-F4>=[1;2S
"    set <S-F5>=[15;2~
"    set <S-F6>=[17;2~
"    set <S-F7>=[18;2~
"    set <S-F8>=[19;2~
"    set <S-F9>=[20;2~
"    set <S-F10>=[21;2~
"    set <S-F11>=[23;2~
"    set <S-F12>=[24;2~
"    set <S-Left>=[1;2D
"    set <S-Right>=[1;2C
"    set <S-Up>=[1;2A
"    set <S-Down>=[1;2B
"    set <S-Home>=[1;2H
"    set <S-End>=[1;2F
"    set <C-Home>=[1;5H
"    set <C-End>=[1;5F
"    set <S-Insert>=[2;2~
"    set <S-Delete>=[3;2~
"    set <F13>=[27;2;13~
"endif
"" fix xterm keys {{{
"map  <Esc>[1;2A <S-Up>
"map! <Esc>[1;2A <S-Up>
"map  <Esc>[1;2B <S-Down>
"map! <Esc>[1;2B <S-Down>
"map  <Esc>[1;2C <S-Right>
"map! <Esc>[1;2C <S-Right>
"map  <Esc>[1;2D <S-Left>
"map! <Esc>[1;2D <S-Left>
"map  <Esc>[1;2F <S-End>
"map! <Esc>[1;2F <S-End>
"map  <Esc>[1;2H <S-Home>
"map! <Esc>[1;2H <S-Home>
"map  <Esc>[2;2~ <S-Insert>
"map! <Esc>[2;2~ <S-Insert>
"map  <Esc>[3;2~ <S-Delete>
"map! <Esc>[3;2~ <S-Delete>
"map  <Esc>[5;2~ <S-PageUp>
"map! <Esc>[5;2~ <S-PageUp>
"map  <Esc>[6;2~ <S-PageDown>
"map! <Esc>[6;2~ <S-PageDown>
"" Fix up M-motion keys
"map  <Esc>[1;3A <M-Up>
"map! <Esc>[1;3A <M-Up>
"map  <Esc>[1;3B <M-Down>
"map! <Esc>[1;3B <M-Down>
"map  <Esc>[1;3C <M-Right>
"map! <Esc>[1;3C <M-Right>
"map  <Esc>[1;3D <M-Left>
"map! <Esc>[1;3D <M-Left>
"map  <Esc>[1;3F <M-End>
"map! <Esc>[1;3F <M-End>
"map  <Esc>[1;3H <M-Home>
"map! <Esc>[1;3H <M-Home>
"map  <Esc>[2;3~ <M-Insert>
"map! <Esc>[2;3~ <M-Insert>
"map  <Esc>[3;3~ <M-Delete>
"map! <Esc>[3;3~ <M-Delete>
"map  <Esc>[5;3~ <M-PageUp>
"map! <Esc>[5;3~ <M-PageUp>
"map  <Esc>[6;3~ <M-PageDown>
"map! <Esc>[6;3~ <M-PageDown>

"" Fix up S-M-motion keys
"map  <Esc>[1;4A <S-M-Up>
"map! <Esc>[1;4A <S-M-Up>
"map  <Esc>[1;4B <S-M-Down>
"map! <Esc>[1;4B <S-M-Down>
"map  <Esc>[1;4C <S-M-Right>
"map! <Esc>[1;4C <S-M-Right>
"map  <Esc>[1;4D <S-M-Left>
"map! <Esc>[1;4D <S-M-Left>
"map  <Esc>[1;4F <S-M-End>
"map! <Esc>[1;4F <S-M-End>
"map  <Esc>[1;4H <S-M-Home>
"map! <Esc>[1;4H <S-M-Home>
"map  <Esc>[2;4~ <S-M-Insert>
"map! <Esc>[2;4~ <S-M-Insert>
"map  <Esc>[3;4~ <S-M-Delete>
"map! <Esc>[3;4~ <S-M-Delete>
"map  <Esc>[5;4~ <S-M-PageUp>
"map! <Esc>[5;4~ <S-M-PageUp>
"map  <Esc>[6;4~ <S-M-PageDown>
"map! <Esc>[6;4~ <S-M-PageDown>

"" Fix up C-motion keys
"map  <Esc>[1;5A <C-Up>
"map! <Esc>[1;5A <C-Up>
"map  <Esc>[1;5B <C-Down>
"map! <Esc>[1;5B <C-Down>
"map  <Esc>[1;5C <C-Right>
"map! <Esc>[1;5C <C-Right>
"map  <Esc>[1;5D <C-Left>
"map! <Esc>[1;5D <C-Left>
"map  <Esc>[1;5F <C-End>
"map! <Esc>[1;5F <C-End>
"map  <Esc>[1;5H <C-Home>
"map! <Esc>[1;5H <C-Home>
"map  <Esc>[2;5~ <C-Insert>
"map! <Esc>[2;5~ <C-Insert>
"map  <Esc>[3;5~ <C-Delete>
"map! <Esc>[3;5~ <C-Delete>
"map  <Esc>[5;5~ <C-PageUp>
"map! <Esc>[5;5~ <C-PageUp>
"map  <Esc>[6;5~ <C-PageDown>
"map! <Esc>[6;5~ <C-PageDown>

"" Fix up S-C-motion keys
"map  <Esc>[1;6A <S-C-Up>
"map! <Esc>[1;6A <S-C-Up>
"map  <Esc>[1;6B <S-C-Down>
"map! <Esc>[1;6B <S-C-Down>
"map  <Esc>[1;6C <S-C-Right>
"map! <Esc>[1;6C <S-C-Right>
"map  <Esc>[1;6D <S-C-Left>
"map! <Esc>[1;6D <S-C-Left>
"map  <Esc>[1;6F <S-C-End>
"map! <Esc>[1;6F <S-C-End>
"map  <Esc>[1;6H <S-C-Home>
"map! <Esc>[1;6H <S-C-Home>
"map  <Esc>[2;6~ <S-C-Insert>
"map! <Esc>[2;6~ <S-C-Insert>
"map  <Esc>[3;6~ <S-C-Delete>
"map! <Esc>[3;6~ <S-C-Delete>
"map  <Esc>[5;6~ <S-C-PageUp>
"map! <Esc>[5;6~ <S-C-PageUp>
"map  <Esc>[6;6~ <S-C-PageDown>
"map! <Esc>[6;6~ <S-C-PageDown>

"" Fix up M-C-motion keys
"map  <Esc>[1;7A <M-C-Up>
"map! <Esc>[1;7A <M-C-Up>
"map  <Esc>[1;7B <M-C-Down>
"map! <Esc>[1;7B <M-C-Down>
"map  <Esc>[1;7C <M-C-Right>
"map! <Esc>[1;7C <M-C-Right>
"map  <Esc>[1;7D <M-C-Left>
"map! <Esc>[1;7D <M-C-Left>
"map  <Esc>[1;7F <M-C-End>
"map! <Esc>[1;7F <M-C-End>
"map  <Esc>[1;7H <M-C-Home>
"map! <Esc>[1;7H <M-C-Home>
"map  <Esc>[2;7~ <M-C-Insert>
"map! <Esc>[2;7~ <M-C-Insert>
"map  <Esc>[3;7~ <M-C-Delete>
"map! <Esc>[3;7~ <M-C-Delete>
"map  <Esc>[5;7~ <M-C-PageUp>
"map! <Esc>[5;7~ <M-C-PageUp>
"map  <Esc>[6;7~ <M-C-PageDown>
"map! <Esc>[6;7~ <M-C-PageDown>

"" Fix up S-M-C-motion keys
"map  <Esc>[1;8A <S-M-C-Up>
"map! <Esc>[1;8A <S-M-C-Up>
"map  <Esc>[1;8B <S-M-C-Down>
"map! <Esc>[1;8B <S-M-C-Down>
"map  <Esc>[1;8C <S-M-C-Right>
"map! <Esc>[1;8C <S-M-C-Right>
"map  <Esc>[1;8D <S-M-C-Left>
"map! <Esc>[1;8D <S-M-C-Left>
"map  <Esc>[1;8F <S-M-C-End>
"map! <Esc>[1;8F <S-M-C-End>
"map  <Esc>[1;8H <S-M-C-Home>
"map! <Esc>[1;8H <S-M-C-Home>
"map  <Esc>[2;8~ <S-M-C-Insert>
"map! <Esc>[2;8~ <S-M-C-Insert>
"map  <Esc>[3;8~ <S-M-C-Delete>
"map! <Esc>[3;8~ <S-M-C-Delete>
"map  <Esc>[5;8~ <S-M-C-PageUp>
"map! <Esc>[5;8~ <S-M-C-PageUp>
"map  <Esc>[6;8~ <S-M-C-PageDown>
"map! <Esc>[6;8~ <S-M-C-PageDown>

"" M-[character]
"map  <Esc>0 <A-0>
"map! <Esc>0 <A-0>
"map  <Esc>1 <A-1>
"map! <Esc>1 <A-1>
"map  <Esc>2 <A-2>
"map! <Esc>2 <A-2>
"map  <Esc>3 <A-3>
"map! <Esc>3 <A-3>
"map  <Esc>4 <A-4>
"map! <Esc>4 <A-4>
"map  <Esc>5 <A-5>
"map! <Esc>5 <A-5>
"map  <Esc>6 <A-6>
"map! <Esc>6 <A-6>
"map  <Esc>7 <A-7>
"map! <Esc>7 <A-7>
"map  <Esc>8 <A-8>
"map! <Esc>8 <A-8>
"map  <Esc>9 <A-9>
"map! <Esc>9 <A-9>
"map  <Esc>- <A-->
"map! <Esc>- <A-->
"map  <Esc>= <A-=>
"map! <Esc>= <A-=>

"" urxvt home / end
"" the second is for insert mode
"map  <Esc>[7~ <Home>
"map  <Esc>[8~ <End>
"imap <Esc>[7~ <Home>
"imap <Esc>[8~ <End>
