#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) whenever an unbound key combo is used,
# with the key combo as its first argument and the path of the current image
# as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case "$1" in
# "C-c")
# 	echo -n "$2" | xsel -i ;;
"C-e")
	urxvt -bg "#444" -fg "#eee" -sl 0 -title "$2" -e sh -c "exiv2 pr -q -pa '$2' | less" & ;;
"C-g")
	gimp "$2" & ;;
"C-comma")
	exec jpegtran -rotate 270 -copy all -outfile "$2" "$2" ;;
"C-period")
	exec jpegtran -rotate  90 -copy all -outfile "$2" "$2" ;;
"C-slash")
	exec jpegtran -rotate 180 -copy all -outfile "$2" "$2" ;;
"C-less")
	exec mogrify -rotate -90 "$2" ;;
"C-greater")
	exec mogrify -rotate +90 "$2" ;;
"C-question")
	exec mogrify -rotate 180 "$2" ;;
esac
#/* open current image with given program: */
#/*  { true, XK_g, it_open_with, (arg_t) "gimp" }, */
#/*  */
#/*  #<{(| run shell command line on current file ("$SXIV_IMG"): |)}># */
#/*  { true, XK_less, it_shell_cmd, (arg_t) \ */
#/*  "mogrify -rotate -90 \"$SXIV_IMG\"" }, */
#/*  { true, XK_greater, it_shell_cmd, (arg_t) \ */
#/*  "mogrify -rotate +90 \"$SXIV_IMG\"" }, */
#/*  { true, XK_backslash, it_shell_cmd, (arg_t) \ */
#/*  "jpegtran -flip horizontal -copy all -outfile \"$SXIV_IMG\" \"$SXIV_IMG\"" }, */
#/*  { true, XK_bar, it_shell_cmd, (arg_t) \ */
#/*  "jpegtran -flip vertical -copy all -outfile \"$SXIV_IMG\" \"$SXIV_IMG\"" }, */
#/*  { true, XK_comma, it_shell_cmd, (arg_t) \ */
#/*  "jpegtran -rotate 270 -copy all -outfile \"$SXIV_IMG\" \"$SXIV_IMG\"" }, */
#/*  { true, XK_period, it_shell_cmd, (arg_t) \ */
#/*  "jpegtran -rotate 90 -copy all -outfile \"$SXIV_IMG\" \"$SXIV_IMG\"" }, */
#/*  { true, XK_d, it_shell_cmd, (arg_t) \ */
#/*              "mv \"$SXIV_IMG\" ~/trash/1st-level/pic" }, */
#/*  { true, XK_c, it_shell_cmd, (arg_t) \ */
#/*              "catapult copy \"$SXIV_IMG\"" }, */
#/*  #<{(| { true, XK_m, it_shell_cmd, (arg_t) \ |)}># */
#/*  #<{(|             "catapult move \"$SXIV_IMG\"" }, |)}># */
#/*  { true, XK_r, it_shell_cmd, (arg_t) \ */
#/*              "catapult rename \"$SXIV_IMG\"" }, */
#/*  #<{(| { true, XK_semicolon, it_shell_cmd, (arg_t) \ |)}># */
#/*  #<{(|             "catapult repeat \"$SXIV_IMG\"" }, |)}># */
#/*  { false, XK_c, it_shell_cmd, (arg_t) \ */
#/*              "/home/neg/bin/scripts/copy_args \"$SXIV_IMG\"" }, */
#/*  { false, XK_slash, it_shell_cmd, (arg_t) \ */
#/*              "browse_parent \"$SXIV_IMG\"" }, */
#/*  { true, XK_1, it_shell_cmd, (arg_t) \ */
#/*              "hsetroot -full \"$SXIV_IMG\"" }, */
#/*  { true, XK_2, it_shell_cmd, (arg_t) \ */
#/*              "hsetroot -fill \"$SXIV_IMG\"" }, */
#/*  { true, XK_3, it_shell_cmd, (arg_t) \ */
#/*              "hsetroot -center \"$SXIV_IMG\"" }, */
#

