#!/bin/sh

GENERAL_GAP=10
BW=4
PANEL_STATUS_HEIGHT=22

waitron wm_config border_width ${BW}
waitron wm_config color_focused "$(xrq '*.color17' | sed 's/\#/0x/')"
waitron wm_config color_unfocused "$(xrq '*.color2' | sed 's/\#/0x/')"
waitron wm_config gap_width all $GENERAL_GAP
waitron wm_config gap_width top $(( 2 * (GENERAL_GAP + BW) + PANEL_STATUS_HEIGHT ))
waitron wm_config grid_gap_width $(( 2 * GENERAL_GAP ))
waitron wm_config cursor_position middle
waitron wm_config groups_nr 20
waitron wm_config enable_sloppy_focus false
waitron wm_config sticky_windows true
waitron wm_config enable_borders true

#~/bin/focus_watcher.sh
